baseURL = "https://blavad.github.io/"
languageCode = "en-us"
title = "David Albert"
linkedin = "https://www.linkedin.com/in/david-albert-a767a4160/"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
    category = "categories"
