name: Deploy to GitHub pages

# Controls when the action will run.
# In this case, when changes are made to the source branch
on:
  push:
    branches: [ master ]
    
jobs:
  build-and-deploy:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{secrets.SSH_KEY}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
        
# Installs dependencies and generates static files inside the wwwroot folder
#- name: Generate static vuejs files 
#  uses: actions/setup-node@v1
#  with:
#    node-version: '16.x'
#- run: npm install
#- run: npm run build

# Check for broken links (Doesnt play well with autogenerated pages for tags and blogpost listings)
# - run: npm install -g vuepress
# - run: vuepress check-md website

# Copy extra files to the wwwroot folder
# - run: |
#     cp ./README.md ./wwwroot/README.md
#     cp ./LICENSE ./wwwroot/LICENSE
# Create a fresh git repo in wwwroot
    - name: deploy to gh-pages
    - uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
