# Controls when the action will run.
# In this case, when changes are made to the source branch
name: Deploy to GitHub pages
'on':
  push:
    branches:
      - main
    
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Run install (with yarn)
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Run production build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command
        
    # Create a fresh git repo in wwwroot
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
